Repository SOPT-Joint-Seminar-Toss/Toss_iOS, pull requests merged in 2023-05, with the labels that each got.

#5 [Fix] #4 - 이미지 에셋 관련 오류 수정
  Toss_iOS/Image.swift
  Toss_iOS/Toss_iOS/Global/Extension/UIImageView+.swift
Labels: 🔨 Fix, 🦈 희재

#9 [Style] #3 - 토스 페이 메인 상품 페이지 UI 구현 #3
  Toss_iOS/Pay/APIModel/PayProductModel.swift
  Toss_iOS/Pay/Cell/HeaderFooterView/PayProductCollectionFooterView.swift
  Toss_iOS/Pay/Cell/HeaderFooterView/PayProductCollectionHeaderView.swift
  Toss_iOS/Pay/Cell/PayProductCollectionViewCell.swift
  Toss_iOS/Pay/View/PayCollectionLayout.swift
  Toss_iOS/Pay/View/PayMainView.swift
  Toss_iOS/Pay/View/PayNavigationView.swift
  Toss_iOS/Pay/View/PayProductView.swift
  Toss_iOS/Pay/View/PaySearchView.swift
  Toss_iOS/Pay/ViewController/BaseViewController.swift
  Toss_iOS/Pay/ViewController/PayViewController.swift
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS/Application/SceneDelegate.swift
  Toss_iOS/Toss_iOS/Data/Pay/APIModel/PayProductModel.swift
  Toss_iOS/Toss_iOS/Global/Constant/Image.swift
  Toss_iOS/Toss_iOS/Global/Extension/UIColor+.swift
  Toss_iOS/Toss_iOS/Global/Extension/UILabel+.swift
  Toss_iOS/Toss_iOS/Global/Extension/UITextField+.swift
  Toss_iOS/Toss_iOS/Presentation/Base/BaseViewController.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/HeaderFooterView/PayProductCollectionFooterView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/HeaderFooterView/PayProductCollectionHeaderView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/PayProductCollectionViewCell.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/View/PayCollectionLayout.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/View/PayMainView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/View/PayNavigationView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/View/PayProductView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/View/PaySearchView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/ViewController/PayViewController.swift
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/icn_search.imageset/Contents.json
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/icn_search.imageset/Group 5274.png
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/icn_search.imageset/Group 5274@2x.png
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/icn_search.imageset/Group 5274@3x.png
Labels: ✨ Feat, 🦈 희재

#12 [Style] #10 - 토스 페이 메인 브랜드 관련 페이지 UI 구현
  Toss_iOS/Pay/View/PayCollectionLayout.swift
  Toss_iOS/Pay/View/PayMainView.swift
  Toss_iOS/Pay/View/PayNavigationView.swift
  Toss_iOS/Pay/View/PayProductCollectionView.swift
  Toss_iOS/Pay/View/PaySearchView.swift
  Toss_iOS/Pay/ViewController/PayViewController.swift
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS/Data/Pay/APIModel/PayPopularConModel.swift
  Toss_iOS/Toss_iOS/Data/Pay/Model/PayBrandConModel.swift
  Toss_iOS/Toss_iOS/Data/Pay/Model/PayCashBackModel.swift
  Toss_iOS/Toss_iOS/Data/Pay/Model/PayPopularBrandModel.swift
  Toss_iOS/Toss_iOS/Global/Constant/Image.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/HeaderFooterView/PayBrandConCollectionViewHeaderView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/HeaderFooterView/PayCashBackTableFooterView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/HeaderFooterView/PayCashBackTableHeaderView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/HeaderFooterView/PayPopularBrandFooterView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/HeaderFooterView/PayPopularBrandTableHeaderView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/HeaderFooterView/PayPopularConTableHeaderView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/PayBrandConCollectionViewCell.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/PayCashBackTableViewCell.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/PayPopularBrandTableViewCell.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/PayPopularConTableViewCell.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/View/PayBrandConCollectionView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/View/PayCashBackTableView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/View/PayPopularBrandTableView.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/View/PayPopularConTableView.swift
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/BrandCon/brandCon_pizza.imageset/Contents.json
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/BrandCon/brandCon_pizza.imageset/icn_pizza.png
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/BrandCon/brandCon_pizza.imageset/icn_pizza@2x.png
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/BrandCon/brandCon_pizza.imageset/icn_pizza@3x.png
Labels: ✨ Feat, 🦈 희재

#16 [Feat] #14 - MainViewController UI 구현
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS.xcodeproj/project.xcworkspace/xcuserdata/ryuchanghwi.xcuserdatad/UserInterfaceState.xcuserstate
  Toss_iOS/Toss_iOS/Application/SceneDelegate.swift
  Toss_iOS/Toss_iOS/Global/Extension/UIFont+.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainSectionCellView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainSectionView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainViewController.swift
  Toss_iOS/Toss_iOS/Presentation/Main/SubSectionButton.swift
  Toss_iOS/Toss_iOS/Presentation/Main/SubSectionView.swift
Labels: ✨ Feat, 🐋 창휘

#13 [Feat] #11 - TabBarController 구현
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS.xcodeproj/project.xcworkspace/xcuserdata/ryuchanghwi.xcuserdatad/UserInterfaceState.xcuserstate
  Toss_iOS/Toss_iOS/Application/SceneDelegate.swift
  Toss_iOS/Toss_iOS/Global/Base/TabBarCellView.swift
  Toss_iOS/Toss_iOS/Global/Base/TabBarController.swift
  Toss_iOS/Toss_iOS/Global/Extension/TabBarController.swift
  Toss_iOS/Toss_iOS/Global/Extension/UIFont+.swift
  Toss_iOS/Toss_iOS/Presentation/Base/TestCell.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainSectionCellView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainSectionView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainViewController.swift
  Toss_iOS/Toss_iOS/Presentation/Main/SubSectionButton.swift
  Toss_iOS/Toss_iOS/Presentation/Main/SubSectionView.swift
  Toss_iOS/Toss_iOS/Presentation/TabBarController.swift
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/icn_tosspay.imageset/Contents.json
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/icn_tosspay.imageset/icn_tosspay.png
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/icn_tosspay.imageset/icn_tosspay@2x.png
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/icn_tosspay.imageset/icn_tosspay@3x.png
Labels: ✨ Feat, 🐋 창휘

#29 [Nerwork] 네트워크 프로젝트 세팅 #28
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS/Data/Common/VoidResult.swift
  Toss_iOS/Toss_iOS/Network/Foundation/APIConstants.swift
  Toss_iOS/Toss_iOS/Network/Foundation/AlamofireLogger.swift
  Toss_iOS/Toss_iOS/Network/Foundation/BaseAPI.swift
  Toss_iOS/Toss_iOS/Network/Foundation/BaseTargetType.swift
  Toss_iOS/Toss_iOS/Network/Foundation/Config.swift
  Toss_iOS/Toss_iOS/Network/Foundation/GenericResponse.swift
  Toss_iOS/Toss_iOS/Network/Foundation/NetworkResult.swift
  Toss_iOS/Toss_iOS/Network/Foundation/SimpleResponse.swift
Labels: ✨ Feat, 🦈 희재

#34 [Network] #30 - 인기 브랜드콘 서버 통신
  Toss_iOS/Pay/ViewController/BaseViewController.swift
  Toss_iOS/Pay/ViewController/PayViewController.swift
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS/Data/Pay/APIModel/PayPopularConModel.swift
  Toss_iOS/Toss_iOS/Network/Foundation/APIConstants.swift
  Toss_iOS/Toss_iOS/Network/Pay/PayAPI.swift
  Toss_iOS/Toss_iOS/Network/Pay/PayService.swift
  Toss_iOS/Toss_iOS/Presentation/Pay/Cell/PayPopularConTableViewCell.swift
Labels: ✨ Feat, 🦈 희재

#31 [Feat] 토스페이 구매하기 페이지 구현 완료
  Toss_iOS/Toss_iOS.xcodeproj/project.xcworkspace/xcuserdata/shinjiwon.xcuserdatad/UserInterfaceState.xcuserstate
  Toss_iOS/Toss_iOS/Application/SceneDelegate.swift
  Toss_iOS/Toss_iOS/Global/Constant/Image.swift
  Toss_iOS/Toss_iOS/Global/Extension/UIFont+.swift
  Toss_iOS/Toss_iOS/Presentation/Gift/GiftViewController.swift
Labels: ✨ Feat, 🐬 지원

#41 [Network] 홈 메인 자산 API 구현
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS.xcodeproj/project.xcworkspace/xcuserdata/ryuchanghwi.xcuserdatad/UserInterfaceState.xcuserstate
  Toss_iOS/Toss_iOS/Data/Main/MainAssetResponse.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainViewController.swift
Labels: ✨ Feat, 🐋 창휘

#38 [Style] 홈 탭 소비 섹션 스크롤 시 애니메이션 구현
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS.xcodeproj/project.xcworkspace/xcuserdata/ryuchanghwi.xcuserdatad/UserInterfaceState.xcuserstate
  Toss_iOS/Toss_iOS.xcodeproj/xcshareddata/xcschemes/Toss_iOS.xcscheme
  Toss_iOS/Toss_iOS/Data/Main/MainAssetResponse.swift
  Toss_iOS/Toss_iOS/Presentation/Main/ConsumptionSectionView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainSectionView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainView.swift
  Toss_iOS/Toss_iOS/Presentation/Main/MainViewController.swift
Labels: ✨ Feat, 🐋 창휘

#40 [Network] #35 - 공동 구매 API 서버 통신 구현
  Toss_iOS/Pay/APIModel/PayProductModel.swift
  Toss_iOS/Pay/Cell/HeaderFooterView/PayProductCollectionHeaderView.swift
  Toss_iOS/Pay/Cell/PayProductCollectionViewCell.swift
  Toss_iOS/Pay/View/PayCollectionLayout.swift
  Toss_iOS/Pay/View/PayProductCollectionView.swift
  Toss_iOS/Pay/ViewController/PayViewController.swift
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS/Data/Pay/Model/PayTimeModel.swift
  Toss_iOS/Toss_iOS/Global/Constant/Image.swift
  Toss_iOS/Toss_iOS/Network/Pay/PayAPI.swift
  Toss_iOS/Toss_iOS/Network/Pay/PayService.swift
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/Brand/icn_profile2.imageset/Contents.json
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/Brand/icn_profile2.imageset/img_profiles2.png
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/Brand/icn_profile2.imageset/img_profiles2@2x.png
  Toss_iOS/Toss_iOS/Resource/Assets.xcassets/Brand/icn_profile2.imageset/img_profiles2@3x.png
Labels: ✨ Feat, 🦈 희재

#46 [Network] 선물하기 API 구현
  Toss_iOS/Toss_iOS.xcodeproj/project.pbxproj
  Toss_iOS/Toss_iOS.xcodeproj/project.xcworkspace/xcuserdata/ryuchanghwi.xcuserdatad/UserInterfaceState.xcuserstate
  Toss_iOS/Toss_iOS/Data/Gift/GiftResponse.swift
  Toss_iOS/Toss_iOS/Presentation/Gift/GiftcardViewController.swift
  Toss_iOS/Toss_iOS/Presentation/Gift/ToastMessageViewController.swift
Labels: ✨ Feat, 🐋 창휘

#47 [Feat] #45 - 토스페이 뷰 컨트롤러에서 상품 상세 뷰 컨트롤러로 이동하기
  Toss_iOS/Pay/View/PayCollectionLayout.swift
  Toss_iOS/Pay/ViewController/PayViewController.swift
  Toss_iOS/Toss_iOS/Application/SceneDelegate.swift
  Toss_iOS/Toss_iOS/Presentation/Gift/GiftViewController.swift
Labels: ✨ Feat, 🦈 희재

#52 [Fix] 하트버튼 오류 해결#51
  Toss_iOS/Toss_iOS.xcodeproj/project.xcworkspace/xcuserdata/shinjiwon.xcuserdatad/UserInterfaceState.xcuserstate
  Toss_iOS/Toss_iOS/Presentation/Gift/GiftViewController.swift
Labels: 🔨 Fix, 🐬 지원
